//   chat_customization.dart
//   MobileMessagingFlutter
//
//   Copyright (c) 2016-2026 Infobip Limited
//   Licensed under the Apache License, Version 2.0
//

library chat_customization;

import 'package:infobip_mobilemessaging/models/configurations/configuration.dart';

ChatCustomization customBranding = ChatCustomization(
  chatStatusBarBackgroundColor: '#673AB7',
  chatStatusBarIconsColorMode: 'dark',
  chatToolbar: ToolbarCustomization(
    titleTextAppearance: 'TextAppearance_AppCompat_Title',
    titleTextColor: '#FFFFFF',
    titleText: 'Some new title',
    titleCentered: true,
    backgroundColor: '#673AB7',
    navigationIcon: 'assets/ic_back.png',
    navigationIconTint: '#FFFFFF',
    subtitleTextAppearance: 'TextAppearance_AppCompat_Subtitle',
    subtitleTextColor: '#FFFFFF',
    subtitleText: '#1',
    subtitleCentered: true,
  ),
  attachmentPreviewToolbar: ToolbarCustomization(
    titleTextAppearance: 'TextAppearance_AppCompat_Title',
    titleTextColor: '#212121',
    titleText: 'Attachment preview',
    titleCentered: true,
    backgroundColor: '#673AB7',
    navigationIcon: 'assets/ic_back.png',
    navigationIconTint: '#FFFFFF',
    subtitleTextAppearance: 'TextAppearance_AppCompat_Subtitle',
    subtitleTextColor: '#FFFFFF',
    subtitleText: 'Attachment preview subtitle',
    subtitleCentered: false,
  ),
  attachmentPreviewToolbarSaveMenuItemIcon: 'assets/ic_download.png',
  attachmentPreviewToolbarMenuItemsIconTint: '#9E9E9E',
  networkErrorText: 'Network error',
  networkErrorTextColor: '#FF5722',
  networkErrorTextAppearance: 'TextAppearance_AppCompat_Medium',
  networkErrorLabelBackgroundColor: '#3F51B5',
  networkErrorIconTint: '#FFC107',
  chatBannerErrorTextColor: '#FF6F00',
  chatBannerErrorTextAppearance: 'TextAppearance_AppCompat_Medium',
  chatBannerErrorBackgroundColor: '#FFE0B2',
  chatBannerErrorIconTint: '#E65100',
  chatFullScreenErrorTitleText: 'Oops! Something went wrong',
  chatFullScreenErrorTitleTextColor: '#E91E63',
  chatFullScreenErrorTitleTextAppearance: 'TextAppearance_AppCompat_Large',
  chatFullScreenErrorDescriptionText: 'Please check your connection and try again',
  chatFullScreenErrorDescriptionTextColor: '#00BCD4',
  chatFullScreenErrorDescriptionTextAppearance: 'TextAppearance_AppCompat_Body1',
  chatFullScreenErrorBackgroundColor: '#e06666',
  chatFullScreenErrorIconTint: '#FF9800',
  chatFullScreenErrorRefreshButtonText: 'Retry',
  chatFullScreenErrorRefreshButtonTextColor: '#4CAF50',
  chatFullScreenErrorRefreshButtonVisible: true,
  chatBackgroundColor: '#FFFFFF',
  chatProgressBarColor: '#9E9E9E',
  chatInputTextAppearance: 'TextAppearance_AppCompat',
  chatInputTextColor: '#212121',
  chatInputBackgroundColor: '#D1C4E9',
  chatInputHintText: 'Input Message',
  chatInputHintTextColor: '#212121',
  chatInputAttachmentIcon: 'assets/ic_add_circle.png',
  chatInputAttachmentIconTint: '#9E9E9E',
  chatInputAttachmentBackgroundDrawable: 'assets/ic_circle.png',
  chatInputAttachmentBackgroundColor: '#673AB7',
  chatInputSendIcon: 'assets/ic_send.png',
  chatInputSendIconTint: '#9E9E9E',
  chatInputSendBackgroundDrawable: 'assets/ic_circle.png',
  chatInputSendBackgroundColor: '#673AB7',
  chatInputSeparatorLineColor: '#BDBDBD',
  chatInputSeparatorLineVisible: true,
  chatInputCursorColor: '#9E9E9E',
  chatInputCharCounterTextAppearance: 'TextAppearance_AppCompat_Subtitle',
  chatInputCharCounterDefaultColor: '#d0d32f',
  chatInputCharCounterAlertColor: '#2fd358',
  shouldHandleKeyboardAppearance: true,
);

